#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import h5py

f = h5py.File('./table.h5', 'r')
a = f['resonance/xsection/scalar'].attrs
ss = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])

X = f['resonance/xsection/scalar/0'].value
dpzX = f['resonance/xsection/vector/3'].value
dpx2X = f['resonance/xsection/tensor/5'].value
dpy2X = f['resonance/xsection/tensor/10'].value
dpz2X = f['resonance/xsection/tensor/15'].value

plt.plot(ss, X[:,5],'rD')
plt.show()

R = f['resonance/rate/scalar/0'].value
a = f['resonance/rate/scalar'].attrs
E = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
plt.plot(E, R[:,5],'rD')
#plt.plot(T, R[5,:]/T)
plt.show()

R0 = f['resonance/rate/vector/0'].value
R3 = f['resonance/rate/vector/3'].value
a = f['resonance/rate/vector'].attrs
E = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
plt.plot(E, -R0[:,5],'rD')
plt.plot(E, -R3[:,5],'bD')
plt.show()

R00 = f['resonance/rate/tensor/0'].value
R11 = f['resonance/rate/tensor/5'].value
R22 = f['resonance/rate/tensor/10'].value
R33 = f['resonance/rate/tensor/15'].value
a = f['resonance/rate/tensor'].attrs
E = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
qxx = R11/T**3
qyy = R22/T**3
qzz = (R33 - R3**2/R)/T**3
plt.plot(T, (qxx+qyy)[3,:])
plt.show()
a = f['resonance/rate/tensor'].attrs
E = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
plt.plot(E, qxx[:,5],'r-')
plt.plot(E, qyy[:,5],'g-')
plt.plot(E, qzz[:,5],'b-')
plt.show()

