#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import h5py

f = h5py.File('./table.h5', 'r')

for process,c in zip(['Qq2Qq', 'Qg2Qg', 'resonance'], ['r','g','b']):
	a = f[process+'/xsection/scalar'].attrs
	ss = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
	T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
	Y = f[process+'/xsection/scalar/0'].value
	plt.plot(ss, Y[:,3], label=process, color=c)
plt.show()

for process,c in zip(['Qq2Qq', 'Qg2Qg', 'resonance'], ['r','g','b']):
	a = f[process+'/rate/scalar'].attrs
	ss = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
	T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
	Y = f[process+'/rate/scalar/0'].value
	plt.plot(T, Y[20,:], label=process, color=c)
plt.show()


for process,c in zip(['Qq2Qq', 'Qg2Qg', 'resonance'], ['r','g','b']):
	a = f[process+'/rate/scalar'].attrs
	ss = np.linspace(a['low-0'], a['high-0'], a['shape-0'])
	T = np.linspace(a['low-1'], a['high-1'], a['shape-1'])
	R = f[process+'/rate/scalar/0'].value
	Rz = f[process+'/rate/vector/3'].value
	Rxx = f[process+'/rate/tensor/5'].value
	Rzz = f[process+'/rate/tensor/15'].value
	Rzz = Rzz - Rz**2/R
	plt.plot(T, Rxx.T/np.outer(T**3, np.ones_like(ss)*ss), label=process, color=c)
plt.show()
