#!/bin/bash
#SBATCH --qos regular
#SBATCH --constraint haswell
#SBATCH --nodes 2
#SBATCH --cpus-per-task 1
#SBATCH --time 01:00:00
#SBATCH --license cscratch1
#SBATCH --mail-type ALL
#SBATCH --mail-user wk42@phy.duke.edu
#DW jobdw capacity=10GB access_mode=striped type=scratch
#DW stage_in source=/global/cscratch1/sd/wk42/NewHF/Forjet/LidoConfig/lido_tune1d5.xml destination=$DW_JOB_STRIPED/lido_settings.xml type=file
#DW stage_in source=/global/cscratch1/sd/wk42/NewHF/Forjet/LidoConfig/table-mu1d5.h5 destination=$DW_JOB_STRIPED/table.h5 type=file
#DW stage_in source=/global/cscratch1/sd/wk42/NewHF/Forjet/LidoConfig/pythia-PbPb-5020-setting.txt destination=$DW_JOB_STRIPED/pythia.txt type=file
#DW stage_in source=/global/cscratch1/sd/wk42/NewHF/Forjet/HicAvgEvents/0-10/JetData.h5 destination=$DW_JOB_STRIPED/hydro.h5 type=file
#DW stage_in source=/global/cscratch1/sd/wk42/NewHF/Forjet/HicAvgEvents/0-10/ic.h5 destination=$DW_JOB_STRIPED/ic.h5 type=file
#DW stage_out source=$DW_JOB_STRIPED/results destination=/global/cscratch1/sd/wk42/NewHF/Forjet/mu1d5-Leading-E4T-decay-off type=directory
ls ${DW_JOB_STRIPED}
mkdir ${DW_JOB_STRIPED}/results/
module load gcc cray-hdf5 gsl boost/1.69.0
module list
export HDF5_USE_FILE_LOCKING='FALSE'

for i in {1..100};
	do time srun jet-2Dhydro-couple -y ${DW_JOB_STRIPED}/pythia.txt\
        -s ${DW_JOB_STRIPED}/lido_settings.xml\
        -t ${DW_JOB_STRIPED}/table.h5\
        --hydro ${DW_JOB_STRIPED}/hydro.h5\
        --ic ${DW_JOB_STRIPED}/ic.h5\
        --eid 0 -n 50 \
	-o ${DW_JOB_STRIPED}/results/ \
        --Q0 1.5 > out
done

