.TH "src Directory Reference" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapprox_functions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBapprox_functions\&.h\fP"
.br
.ti -1c
.RI "file \fBasa047\&.cpp\fP"
.br
.ti -1c
.RI "file \fBasa047\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcollision_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcollision_manager\&.h\fP"
.br
.ti -1c
.RI "file \fBconverged\&.h\fP"
.br
.ti -1c
.RI "file \fBcubature\&.h\fP"
.br
.ti -1c
.RI "file \fBHadronize\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHadronize\&.h\fP"
.br
.ti -1c
.RI "file \fBhcubature\&.cpp\fP"
.br
.ti -1c
.RI "file \fBintegrator\&.h\fP"
.br
.ti -1c
.RI "file \fBLangevin\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLangevin\&.h\fP"
.br
.ti -1c
.RI "file \fBlido\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlido\&.h\fP"
.br
.ti -1c
.RI "file \fBlogo\&.h\fP"
.br
.ti -1c
.RI "file \fBlorentz\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlorentz\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_elements\&.h\fP"
.br
.ti -1c
.RI "file \fBmatrix_elements_1\-2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_elements_2\-2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_elements_2\-3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMedium_Reader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMedium_Reader\&.h\fP"
.br
.ti -1c
.RI "file \fBminimizer\&.h\fP"
.br
.ti -1c
.RI "file \fBpredefine\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpredefine\&.h\fP"
.br
.ti -1c
.RI "file \fBrandom\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrandom\&.h\fP"
.br
.ti -1c
.RI "file \fBRate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRate\&.h\fP"
.br
.ti -1c
.RI "file \fBsampler\&.h\fP"
.br
.ti -1c
.RI "file \fBsimpleLogger\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsimpleLogger\&.h\fP"
.br
.ti -1c
.RI "file \fBstat\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstat\&.h\fP"
.br
.ti -1c
.RI "file \fBStochasticBase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBStochasticBase\&.h\fP"
.br
.ti -1c
.RI "file \fBTableBase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTableBase\&.h\fP"
.br
.ti -1c
.RI "file \fBvwrapper\&.h\fP"
.br
.ti -1c
.RI "file \fBXsection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBXsection\&.h\fP"
.br
.in -1c
