.TH "src/approx_functions.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/approx_functions.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'lorentz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscalar\fP \fBapprox_X22\fP (std::vector< double > params)"
.br
.ti -1c
.RI "\fBscalar\fP \fBapprox_X22QQbar\fP (std::vector< double > params)"
.br
.ti -1c
.RI "\fBscalar\fP \fBapprox_dX22_max\fP (std::vector< double > params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBscalar\fP approx_dX22_max (std::vector< double > params)"

.SS "\fBscalar\fP approx_X22 (std::vector< double > params)"

.SS "\fBscalar\fP approx_X22QQbar (std::vector< double > params)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
