.TH "src/asa047.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/asa047.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'asa047\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIME_SIZE\fP   40"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnelmin\fP (double fn(double x[]), int n, double start[], double xmin[], double *ynewlo, double reqmin, double step[], int konvge, int kcount, int *icount, int *numres, int *ifault)"
.br
.ti -1c
.RI "void \fBtimestamp\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIME_SIZE   40"

.SH "Function Documentation"
.PP 
.SS "void nelmin (double  fndouble x[], int n, double start[], double xmin[], double * ynewlo, double reqmin, double step[], int konvge, int kcount, int * icount, int * numres, int * ifault)"

.SS "void timestamp (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
