.TH "src/collision_manager.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/collision_manager.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/variant/variant\&.hpp>\fP
.br
\fC#include 'Rate\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcollision_manager\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRate\fP< \fBHS2PP\fP, 2, 2, double(*)(const double, void *)> \fBRate22\fP"
.br
.ti -1c
.RI "typedef \fBRate\fP< \fBHS2PPP\fP, 2, 2, double(*)(const double *, void *)> \fBRate23\fP"
.br
.ti -1c
.RI "typedef \fBEffRate12\fP< 2, double(*)(const double *, void *)> \fBRate12\fP"
.br
.ti -1c
.RI "typedef boost::variant< \fBRate22\fP, \fBRate23\fP, \fBRate12\fP > \fBProcess\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::variant<\fBRate22\fP, \fBRate23\fP, \fBRate12\fP> \fBProcess\fP"

.SS "typedef \fBEffRate12\fP<2, double(*)(const double*, void*)> \fBRate12\fP"

.SS "typedef \fBRate\fP<\fBHS2PP\fP, 2, 2, double(*)(const double, void*)> \fBRate22\fP"

.SS "typedef \fBRate\fP<\fBHS2PPP\fP, 2, 2, double(*)(const double*, void*)> \fBRate23\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
