.TH "src/collision_manager.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/collision_manager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'collision_manager\&.h'\fP
.br
\fC#include <boost/property_tree/xml_parser\&.hpp>\fP
.br
\fC#include <boost/property_tree/ptree\&.hpp>\fP
.br
\fC#include <boost/variant/get\&.hpp>\fP
.br
\fC#include <boost/any\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include 'matrix_elements\&.h'\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br
\fC#include 'Langevin\&.h'\fP
.br
\fC#include 'random\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
