.TH "src/converged.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/converged.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSQR\fP(x)   ((x) * (x))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBswitch\fP (\fBnorm\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBreturn\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SQR(x)   ((x) * (x))"

.SH "Function Documentation"
.PP 
.SS "switch (\fBnorm\fP)"

.SH "Variable Documentation"
.PP 
.SS "return"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
