.TH "Debye_mass" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debye_mass
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <predefine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebye_mass\fP (const unsigned int _type)"
.br
.ti -1c
.RI "\fB~Debye_mass\fP ()"
.br
.ti -1c
.RI "double \fBget_mD2\fP (double T)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Debye_mass::Debye_mass (const unsigned int _type)"

.SS "Debye_mass::~Debye_mass ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double Debye_mass::get_mD2 (double T)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
