.TH "ele" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ele
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Medium_Reader\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "double \fBval\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ele::i"

.SS "int ele::j"

.SS "double ele::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
