.TH "esterr" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esterr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBval\fP"
.br
.ti -1c
.RI "double \fBerr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double esterr::err"

.SS "double esterr::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
