.TH "ff" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ff
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <predefine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBff\fP (double x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const double \fBvalue\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, const \fBff\fP &x)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ff::ff (double x)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & stream, const \fBff\fP & x)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const double ff::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
