.TH "gsl_vegas< F >" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gsl_vegas< F >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <integrator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgsl_vegas\fP (F f, int limit)"
.br
.ti -1c
.RI "double \fBintegrate\fP (int dim, double *xmin, double *xmax, double &error)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename F > \fBgsl_vegas\fP< F >::\fBgsl_vegas\fP (F f, int limit)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename F > double \fBgsl_vegas\fP< F >::integrate (int dim, double * xmin, double * xmax, double & error)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
