.TH "src/Hadronize.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Hadronize.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Pythia8/Pythia\&.h'\fP
.br
\fC#include 'Hadronize\&.h'\fP
.br
\fC#include 'lorentz\&.h'\fP
.br
\fC#include 'random\&.h'\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFormChain\fP (\fBparticle\fP pi, \fBparticle\fP pf, \fBparticle\fP &front, \fBparticle\fP &back, std::vector< \fBparticle\fP > &chain, std::vector< \fBparticle\fP > &plist, std::vector< \fBparticle\fP > &thermal)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void FormChain (\fBparticle\fP pi, \fBparticle\fP pf, \fBparticle\fP & front, \fBparticle\fP & back, std::vector< \fBparticle\fP > & chain, std::vector< \fBparticle\fP > & plist, std::vector< \fBparticle\fP > & thermal)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
