.TH "heap" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
heap
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "size_t \fBnalloc\fP"
.br
.ti -1c
.RI "\fBheap_item\fP * \fBitems\fP"
.br
.ti -1c
.RI "unsigned \fBfdim\fP"
.br
.ti -1c
.RI "\fBesterr\fP * \fBee\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBesterr\fP* heap::ee"

.SS "unsigned heap::fdim"

.SS "\fBheap_item\fP* heap::items"

.SS "size_t heap::n"

.SS "size_t heap::nalloc"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
