.TH "hypercube" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hypercube
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBdim\fP"
.br
.ti -1c
.RI "double * \fBdata\fP"
.br
.ti -1c
.RI "double \fBvol\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double* hypercube::data"

.SS "unsigned hypercube::dim"

.SS "double hypercube::vol"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
