.TH "JetDenseMediumHadronize" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JetDenseMediumHadronize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hadronize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJetDenseMediumHadronize\fP ()"
.br
.ti -1c
.RI "int \fBhadronize\fP (std::vector< \fBparticle\fP > partons, std::vector< \fBparticle\fP > &hadrons, std::vector< \fBparticle\fP > &thermal_partons, double Q0, double Tf, int level)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JetDenseMediumHadronize::JetDenseMediumHadronize ()"

.SH "Member Function Documentation"
.PP 
.SS "int JetDenseMediumHadronize::hadronize (std::vector< \fBparticle\fP > partons, std::vector< \fBparticle\fP > & hadrons, std::vector< \fBparticle\fP > & thermal_partons, double Q0, double Tf, int level)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
