.TH "lido" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lido
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lido\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlido\fP (std::string setting_path, std::string table_path, std::vector< double > parameters)"
.br
.ti -1c
.RI "int \fBupdate_single_particle\fP (double dt, double T, std::vector< double > v3, \fBparticle\fP &pIn, std::vector< \fBparticle\fP > &pOut_list)"
.br
.ti -1c
.RI "void \fBFreeStream\fP (\fBparticle\fP &p, double dt)"
.br
.ti -1c
.RI "void \fBset_frame\fP (int _choice)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lido::lido (std::string setting_path, std::string table_path, std::vector< double > parameters)"

.SH "Member Function Documentation"
.PP 
.SS "void lido::FreeStream (\fBparticle\fP & p, double dt)"

.SS "void lido::set_frame (int _choice)\fC [inline]\fP"

.SS "int lido::update_single_particle (double dt, double T, std::vector< double > v3, \fBparticle\fP & pIn, std::vector< \fBparticle\fP > & pOut_list)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
