.TH "src/logo.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/logo.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_logo\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_logo (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
