.TH "src/matrix_elements.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/matrix_elements.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'lorentz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBLGV_q2qg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_qg2q\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_g2gg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_gg2g\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_g2qqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gq2gq\fP (const double t, void *params)"
.br
.RI "g(h)1 + q(s)2 --only 1/t^2 term--> g3 + q4 "
.ti -1c
.RI "double \fBdX_gq2gq\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_gg2gg\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBdX_gg2gg\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_qq2qq\fP (const double t, void *params)"
.br
.RI "q(h)1 + q(s)2 --only-t--> q3 + q4, m1=m3, m2=m4=0 "
.ti -1c
.RI "double \fBdX_qq2qq\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_qg2qg\fP (const double t, void *params)"
.br
.RI "q(h)1 + g(s)2 --only-t--> q3 + g4, m1=m3, m2=m4=0 "
.ti -1c
.RI "double \fBdX_qg2qg\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_qg2qg_stu\fP (const double t, void *params)"
.br
.RI "q(h)1 + g(s)2 --s+u+t--> q3 + g4, m1=m3, m2=m4=0 "
.ti -1c
.RI "double \fBdX_qg2qg_stu\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_gg2qqbar\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBdX_gg2qqbar\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_qqbar2qqbar_diff\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBdX_qqbar2qqbar_diff\fP (const double t, void *params)"
.br
.ti -1c
.RI "double \fBM2_qq2qqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qq2qqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_qg2qgg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qg2qgg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gq2gqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gq2gqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gg2ggg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2ggg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_qg2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qg2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gq2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gq2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gg2qgqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2qgqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBM2_gg2gqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2gqqbar\fP (const double *x_, void *params_)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double dX_gg2gg (const double t, void * params)"

.SS "double dX_gg2ggg (const double * x_, void * params_)"

.SS "double dX_gg2gqqbar (const double * x_, void * params_)"

.SS "double dX_gg2qgqbar (const double * x_, void * params_)"

.SS "double dX_gg2qqbar (const double t, void * params)"

.SS "double dX_gq2gq (const double t, void * params)"

.SS "double dX_gq2gqg (const double * x_, void * params_)"

.SS "double dX_gq2qqqbar (const double * x_, void * params_)"

.SS "double dX_qg2qg (const double t, void * params)"

.SS "double dX_qg2qg_stu (const double t, void * params)"

.SS "double dX_qg2qgg (const double * x_, void * params_)"

.SS "double dX_qg2qqqbar (const double * x_, void * params_)"

.SS "double dX_qq2qq (const double t, void * params)"

.SS "double dX_qq2qqg (const double * x_, void * params_)"

.SS "double dX_qqbar2qqbar_diff (const double t, void * params)"

.SS "double LGV_g2gg (const double * x_, void * params_)"

.SS "double LGV_g2qqbar (const double * x_, void * params_)"

.SS "double LGV_gg2g (const double * x_, void * params_)"

.SS "double LGV_q2qg (const double * x_, void * params_)"

.SS "double LGV_qg2q (const double * x_, void * params_)"

.SS "double M2_gg2gg (const double t, void * params)"

.SS "double M2_gg2ggg (const double * x_, void * params_)"

.SS "double M2_gg2gqqbar (const double * x_, void * params_)"

.SS "double M2_gg2qgqbar (const double * x_, void * params_)"

.SS "double M2_gg2qqbar (const double t, void * params)"

.SS "double M2_gq2gq (const double t, void * params)"

.PP
g(h)1 + q(s)2 --only 1/t^2 term--> g3 + q4 
.SS "double M2_gq2gqg (const double * x_, void * params_)"

.SS "double M2_gq2qqqbar (const double * x_, void * params_)"

.SS "double M2_qg2qg (const double t, void * params)"

.PP
q(h)1 + g(s)2 --only-t--> q3 + g4, m1=m3, m2=m4=0 
.SS "double M2_qg2qg_stu (const double t, void * params)"

.PP
q(h)1 + g(s)2 --s+u+t--> q3 + g4, m1=m3, m2=m4=0 
.SS "double M2_qg2qgg (const double * x_, void * params_)"

.SS "double M2_qg2qqqbar (const double * x_, void * params_)"

.SS "double M2_qq2qq (const double t, void * params)"

.PP
q(h)1 + q(s)2 --only-t--> q3 + q4, m1=m3, m2=m4=0 
.SS "double M2_qq2qqg (const double * x_, void * params_)"

.SS "double M2_qqbar2qqbar_diff (const double t, void * params)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
