.TH "src/matrix_elements_2-3.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/matrix_elements_2-3.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'predefine\&.h'\fP
.br
\fC#include 'matrix_elements\&.h'\fP
.br
\fC#include 'lorentz\&.h'\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunpack_three_body_phase_space\fP (const double *x_, void *params_, double &kx, double &ky, double &yk, double &qx, double &qy, double &xbar, double &t, double &Jacobian, bool &status)"
.br
.ti -1c
.RI "void \fBunpack_three_body_phase_space_same\fP (const double *x_, void *params_, double &kx, double &ky, double &yk, double &qx, double &qy, double &xbar, double &t, double &Jacobian, bool &status)"
.br
.ti -1c
.RI "double \fBM2_qq2qqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qq2qqg\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_qg2qgg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qg2qgg\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_qg2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_qg2qqqbar\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_gq2gqg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gq2gqg\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_gg2ggg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2ggg\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_gq2qqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gq2qqqbar\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_gg2qgqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2qgqbar\fP (const double *x_, void *params)"
.br
.ti -1c
.RI "double \fBM2_gg2gqqbar\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBdX_gg2gqqbar\fP (const double *x_, void *params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double dX_gg2ggg (const double * x_, void * params)"

.SS "double dX_gg2gqqbar (const double * x_, void * params)"

.SS "double dX_gg2qgqbar (const double * x_, void * params)"

.SS "double dX_gq2gqg (const double * x_, void * params)"

.SS "double dX_gq2qqqbar (const double * x_, void * params)"

.SS "double dX_qg2qgg (const double * x_, void * params)"

.SS "double dX_qg2qqqbar (const double * x_, void * params)"

.SS "double dX_qq2qqg (const double * x_, void * params)"

.SS "double M2_gg2ggg (const double * x_, void * params_)"

.SS "double M2_gg2gqqbar (const double * x_, void * params_)"

.SS "double M2_gg2qgqbar (const double * x_, void * params_)"

.SS "double M2_gq2gqg (const double * x_, void * params_)"

.SS "double M2_gq2qqqbar (const double * x_, void * params_)"

.SS "double M2_qg2qgg (const double * x_, void * params_)"

.SS "double M2_qg2qqqbar (const double * x_, void * params_)"

.SS "double M2_qq2qqg (const double * x_, void * params_)"

.SS "void unpack_three_body_phase_space (const double * x_, void * params_, double & kx, double & ky, double & yk, double & qx, double & qy, double & xbar, double & t, double & Jacobian, bool & status)"

.SS "void unpack_three_body_phase_space_same (const double * x_, void * params_, double & kx, double & ky, double & yk, double & qx, double & qy, double & xbar, double & t, double & Jacobian, bool & status)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
