.TH "src/matrix_elements_1-2.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/matrix_elements_1-2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'predefine\&.h'\fP
.br
\fC#include 'matrix_elements\&.h'\fP
.br
\fC#include 'lorentz\&.h'\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBLGV_q2qg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_g2gg\fP (const double *x_, void *params_)"
.br
.ti -1c
.RI "double \fBLGV_g2qqbar\fP (const double *x_, void *params_)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double LGV_g2gg (const double * x_, void * params_)"

.SS "double LGV_g2qqbar (const double * x_, void * params_)"

.SS "double LGV_q2qg (const double * x_, void * params_)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
