.TH "src/minimizer.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minimizer.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <gsl/gsl_vector\&.h>\fP
.br
\fC#include <gsl/gsl_min\&.h>\fP
.br
\fC#include <gsl/gsl_multimin\&.h>\fP
.br
\fC#include 'sampler\&.h'\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgsl_minimize_nd< F >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename F > double \fBminimize_1d\fP (F \fBf\fP, std::pair< double, double > const &range, double eps=0\&.01, int max_iter=10, int N=5)"
.br
.ti -1c
.RI "template<typename F > double \fBminimize_nd\fP (F func, const size_t dim, std::vector< double > start, std::vector< double > step, int max_iter=100, double eps=0\&.01)"
.br
.ti -1c
.RI "template<typename F > std::vector< double > \fBMC_maximize\fP (F f_, int n_dims_, std::vector< std::pair< double, double >> const &range, int steps=20)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename F > std::vector<double> MC_maximize (F f_, int n_dims_, std::vector< std::pair< double, double >> const & range, int steps = \fC20\fP)"

.SS "template<typename F > double minimize_1d (F f, std::pair< double, double > const & range, double eps = \fC0\&.01\fP, int max_iter = \fC10\fP, int N = \fC5\fP)"

.SS "template<typename F > double minimize_nd (F func, const size_t dim, std::vector< double > start, std::vector< double > step, int max_iter = \fC100\fP, double eps = \fC0\&.01\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
