.TH "particle" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
particle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <predefine\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpid\fP"
.br
.ti -1c
.RI "int \fBcol\fP"
.br
.ti -1c
.RI "int \fBacol\fP"
.br
.ti -1c
.RI "bool \fBcharged\fP"
.br
.ti -1c
.RI "double \fBmass\fP"
.br
.ti -1c
.RI "double \fBweight\fP"
.br
.ti -1c
.RI "double \fBtau0\fP"
.br
.ti -1c
.RI "double \fBQ0\fP"
.br
.ti -1c
.RI "double \fBQ00\fP"
.br
.ti -1c
.RI "bool \fBis_virtual\fP"
.br
.ti -1c
.RI "double \fBT0\fP"
.br
.ti -1c
.RI "double \fBmfp0\fP"
.br
.ti -1c
.RI "double \fBTf\fP"
.br
.ti -1c
.RI "\fBcoordinate\fP \fBx0\fP"
.br
.ti -1c
.RI "\fBcoordinate\fP \fBx\fP"
.br
.ti -1c
.RI "\fBfourvec\fP \fBp0\fP"
.br
.ti -1c
.RI "\fBfourvec\fP \fBp\fP"
.br
.ti -1c
.RI "\fBfourvec\fP \fBmother_p\fP"
.br
.ti -1c
.RI "std::vector< std::vector< \fBparticle\fP > > \fBradlist\fP"
.br
.ti -1c
.RI "std::vector< double > \fBvcell\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int particle::acol"

.SS "bool particle::charged"

.SS "int particle::col"

.SS "bool particle::is_virtual"

.SS "double particle::mass"

.SS "double particle::mfp0"

.SS "\fBfourvec\fP particle::mother_p"

.SS "\fBfourvec\fP particle::p"

.SS "\fBfourvec\fP particle::p0"

.SS "int particle::pid"

.SS "double particle::Q0"

.SS "double particle::Q00"

.SS "std::vector<std::vector<\fBparticle\fP> > particle::radlist"

.SS "double particle::T0"

.SS "double particle::tau0"

.SS "double particle::Tf"

.SS "std::vector<double> particle::vcell"

.SS "double particle::weight"

.SS "\fBcoordinate\fP particle::x"

.SS "\fBcoordinate\fP particle::x0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
