.TH "Rate< str, N1, N2, F >" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rate< str, N1, N2, F >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rate\&.h>\fP
.PP
Inherits \fBStochasticBase< N1 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRate\fP (std::string Name, std::string configfile, F \fBf\fP)"
.br
.ti -1c
.RI "bool \fBsample\fP (std::vector< double > arg, int incoming_hard_pid, std::vector< \fBfourvec\fP > &FS, std::vector< int > &pids)"
.br
.ti -1c
.RI "void \fBinitX\fP (std::string fname)"
.br
.ti -1c
.RI "void \fBloadX\fP (std::string fname)"
.br
.ti -1c
.RI "bool \fBIsActive\fP (void)"
.br
.ti -1c
.RI "int \fBprocess_id\fP (void)"
.br
.ti -1c
.RI "const char * \fBwhich_implementation\fP () const"
.br
.ti -1c
.RI "\fBRate\fP (std::string Name, std::string configfile, double(*\fBf\fP)(const double, void *))"
.br
.ti -1c
.RI "\fBRate\fP (std::string Name, std::string configfile, double(*\fBf\fP)(const double *, void *))"
.br
.ti -1c
.RI "bool \fBsample\fP (std::vector< double > parameters, int incoming_hard_pid, std::vector< \fBfourvec\fP > &final_states, std::vector< int > &pids)"
.br
.ti -1c
.RI "bool \fBsample\fP (std::vector< double > parameters, int incoming_hard_pid, std::vector< \fBfourvec\fP > &final_states, std::vector< int > &pids)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<char const * str, size_t N1, size_t N2, typename F > \fBRate\fP< str, N1, N2, F >::\fBRate\fP (std::string Name, std::string configfile, F f)"

.SS "\fBRate\fP< \fBHS2PP\fP, 2, 2, double(*)(const double, void *)>::\fBRate\fP (std::string Name, std::string configfile, double(*)(const double, void *) f)"

.SS "\fBRate\fP< \fBHS2PPP\fP, 2, 2, double(*)(const double *, void *)>::\fBRate\fP (std::string Name, std::string configfile, double(*)(const double *, void *) f)"

.SH "Member Function Documentation"
.PP 
.SS "template<char const * str, size_t N1, size_t N2, typename F > void \fBRate\fP< str, N1, N2, F >::initX (std::string fname)\fC [inline]\fP"

.SS "template<char const * str, size_t N1, size_t N2, typename F > bool \fBRate\fP< str, N1, N2, F >::IsActive (void)\fC [inline]\fP"

.SS "template<char const * str, size_t N1, size_t N2, typename F > void \fBRate\fP< str, N1, N2, F >::loadX (std::string fname)\fC [inline]\fP"

.SS "template<char const * str, size_t N1, size_t N2, typename F > int \fBRate\fP< str, N1, N2, F >::process_id (void)\fC [inline]\fP"

.SS "template<char const * str, size_t N1, size_t N2, typename F > bool \fBRate\fP< str, N1, N2, F >::sample (std::vector< double > arg, int incoming_hard_pid, std::vector< \fBfourvec\fP > & FS, std::vector< int > & pids)\fC [virtual]\fP"

.PP
Implements \fBStochasticBase< N1 >\fP\&.
.SS "bool \fBRate\fP< \fBHS2PP\fP, 2, 2, double(*)(const double, void *)>::sample (std::vector< double > parameters, int incoming_hard_pid, std::vector< \fBfourvec\fP > & final_states, std::vector< int > & pids)\fC [virtual]\fP"

.PP
Implements \fBStochasticBase< N1 >\fP\&.
.SS "bool \fBRate\fP< \fBHS2PPP\fP, 2, 2, double(*)(const double *, void *)>::sample (std::vector< double > parameters, int incoming_hard_pid, std::vector< \fBfourvec\fP > & final_states, std::vector< int > & pids)\fC [virtual]\fP"

.PP
Implements \fBStochasticBase< N1 >\fP\&.
.SS "template<char const * str, size_t N1, size_t N2, typename F > const char* \fBRate\fP< str, N1, N2, F >::which_implementation () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
