.TH "region" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
region
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhypercube\fP \fBh\fP"
.br
.ti -1c
.RI "unsigned \fBsplitDim\fP"
.br
.ti -1c
.RI "unsigned \fBfdim\fP"
.br
.ti -1c
.RI "\fBesterr\fP * \fBee\fP"
.br
.ti -1c
.RI "double \fBerrmax\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBesterr\fP* region::ee"

.SS "double region::errmax"

.SS "unsigned region::fdim"

.SS "\fBhypercube\fP region::h"

.SS "unsigned region::splitDim"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
