.TH "rule75genzmalik" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule75genzmalik
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrule\fP \fBparent\fP"
.br
.ti -1c
.RI "double * \fBwidthLambda\fP"
.br
.ti -1c
.RI "double * \fBwidthLambda2\fP"
.br
.ti -1c
.RI "double * \fBp\fP"
.br
.ti -1c
.RI "double \fBweight1\fP"
.br
.ti -1c
.RI "double \fBweight3\fP"
.br
.ti -1c
.RI "double \fBweight5\fP"
.br
.ti -1c
.RI "double \fBweightE1\fP"
.br
.ti -1c
.RI "double \fBweightE3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double * rule75genzmalik::p"

.SS "\fBrule\fP rule75genzmalik::parent"

.SS "double rule75genzmalik::weight1"

.SS "double rule75genzmalik::weight3"

.SS "double rule75genzmalik::weight5"

.SS "double rule75genzmalik::weightE1"

.SS "double rule75genzmalik::weightE3"

.SS "double* rule75genzmalik::widthLambda"

.SS "double * rule75genzmalik::widthLambda2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
