.TH "rule_s" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBdim\fP"
.br
.ti -1c
.RI "unsigned \fBfdim\fP"
.br
.ti -1c
.RI "unsigned \fBnum_points\fP"
.br
.ti -1c
.RI "unsigned \fBnum_regions\fP"
.br
.ti -1c
.RI "double * \fBpts\fP"
.br
.ti -1c
.RI "double * \fBvals\fP"
.br
.ti -1c
.RI "\fBevalError_func\fP \fBevalError\fP"
.br
.ti -1c
.RI "\fBdestroy_func\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBdestroy_func\fP rule_s::destroy"

.SS "unsigned rule_s::dim"

.SS "\fBevalError_func\fP rule_s::evalError"

.SS "unsigned rule_s::fdim"

.SS "unsigned rule_s::num_points"

.SS "unsigned rule_s::num_regions"

.SS "double* rule_s::pts"

.SS "double* rule_s::vals"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
