.TH "SamplerStat" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SamplerStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSamplerStat\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount_1d\fP = 0"
.br
.ti -1c
.RI "static int \fBcount_nd\fP = 0"
.br
.ti -1c
.RI "static int \fBtotal_1d\fP = 0"
.br
.ti -1c
.RI "static int \fBtotal_nd\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SamplerStat::SamplerStat ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int SamplerStat::count_1d = 0\fC [static]\fP"

.SS "int SamplerStat::count_nd = 0\fC [static]\fP"

.SS "int SamplerStat::total_1d = 0\fC [static]\fP"

.SS "int SamplerStat::total_nd = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
