.TH "src/TableBase.cpp" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TableBase.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TableBase\&.h'\fP
.br
\fC#include 'H5Cpp\&.h'\fP
.br
\fC#include 'predefine\&.h'\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'simpleLogger\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBdefault_approximate_function\fP (\fBDvec\fP values)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > T default_approximate_function (\fBDvec\fP values)"
Default approximation function $f=1$ 
.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
