.TH "TransverPositionSampler" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransverPositionSampler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Medium_Reader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransverPositionSampler\fP (std::string filename, int iev)"
.br
.ti -1c
.RI "void \fBSampleXY\fP (double &x, double &y)"
.br
.ti -1c
.RI "double \fBget_Ncoll\fP (void) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransverPositionSampler::TransverPositionSampler (std::string filename, int iev)"

.SH "Member Function Documentation"
.PP 
.SS "double TransverPositionSampler::get_Ncoll (void) const\fC [inline]\fP"

.SS "void TransverPositionSampler::SampleXY (double & x, double & y)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
