.TH "src/vwrapper.h" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vwrapper.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfv_data_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBfv_data_s\fP \fBfv_data\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBfv_data_s\fP \fBfv_data\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
