.TH "walker" 3 "Thu Jul 1 2021" "Duke-Lido" \" -*- nroff -*-
.ad l
.nh
.SH NAME
walker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sampler\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double * \fBposi\fP"
.br
.ti -1c
.RI "double \fBP\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double walker::P"

.SS "double* walker::posi"


.SH "Author"
.PP 
Generated automatically by Doxygen for Duke-Lido from the source code\&.
