var annotated_dup =
[
    [ "AiMS", "classAiMS.html", "classAiMS" ],
    [ "collision_manager", "classcollision__manager.html", "classcollision__manager" ],
    [ "coordinate", "structcoordinate.html", "structcoordinate" ],
    [ "cubeture_nd", "classcubeture__nd.html", "classcubeture__nd" ],
    [ "current", "structcurrent.html", "structcurrent" ],
    [ "Debye_mass", "classDebye__mass.html", "classDebye__mass" ],
    [ "EffRate12", "classEffRate12.html", "classEffRate12" ],
    [ "ele", "structele.html", "structele" ],
    [ "esterr", "structesterr.html", "structesterr" ],
    [ "ff", "classff.html", "classff" ],
    [ "fourvec", "structfourvec.html", "structfourvec" ],
    [ "fv_data_s", "structfv__data__s.html", "structfv__data__s" ],
    [ "gsl_minimize_nd", "classgsl__minimize__nd.html", "classgsl__minimize__nd" ],
    [ "gsl_quad_1d", "classgsl__quad__1d.html", "classgsl__quad__1d" ],
    [ "gsl_vegas", "classgsl__vegas.html", "classgsl__vegas" ],
    [ "heap", "structheap.html", "structheap" ],
    [ "hypercube", "structhypercube.html", "structhypercube" ],
    [ "JetDenseMediumHadronize", "classJetDenseMediumHadronize.html", "classJetDenseMediumHadronize" ],
    [ "lido", "classlido.html", "classlido" ],
    [ "Medium", "classMedium.html", "classMedium" ],
    [ "particle", "structparticle.html", "structparticle" ],
    [ "Rate", "classRate.html", "classRate" ],
    [ "region", "structregion.html", "structregion" ],
    [ "rule75genzmalik", "structrule75genzmalik.html", "structrule75genzmalik" ],
    [ "rule_s", "structrule__s.html", "structrule__s" ],
    [ "SamplerStat", "classSamplerStat.html", "classSamplerStat" ],
    [ "scalar", "structscalar.html", "structscalar" ],
    [ "StochasticBase", "classStochasticBase.html", "classStochasticBase" ],
    [ "TableBase", "classTableBase.html", "classTableBase" ],
    [ "tensor", "structtensor.html", "structtensor" ],
    [ "TransverPositionSampler", "classTransverPositionSampler.html", "classTransverPositionSampler" ],
    [ "walker", "structwalker.html", "structwalker" ],
    [ "Xsection", "classXsection.html", "classXsection" ]
];